# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 628511a8a486ade71bb1f2f2a84ba716666aee7a05a7559e37e3dba9b149ed9f801b7f54b35ae38e454e98ca30f98387ba0ef41f71f098d51fb784cd7a53b0b6

test:
  secret_key_base: 23c4b63df2778a4e05895539c76eacb9acf5e91931112a40fd28aba538cd02da53a805511b7ea35b368e2920ecee25fd546a1b88201c8fffba2227e4c2f78b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
